apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: tuo-nome-immagine-broker:latest
        imagePullPolicy: IfNotPresent
        command: ["/app/consumer"]