apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: kafkaproj:latest
        imagePullPolicy: IfNotPresent
        args:
          - "kafka-0.kafka"
          - "9092"
          - "ordini"
          - "0"
          - "0"
          - "2"
        command: ["/app/consumer"]
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"